logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.name=/tmp/springboot.log


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

server.port=8080

spring.main.banner-mode=console